CREATE TABLE USER_MEMBER (
    UUID_USER_MEMBER SERIAL NOT NULL PRIMARY KEY,
    FULL_NAME VARCHAR(200) NOT NULL,
    NICK_NAME VARCHAR(80),
    LAST_LOGGED_IN DATE,
    CREATE_AT DATE,
    UPDATE_AT DATE
);

CREATE TABLE IMAGE_DATA (
    UUID_IMAGE SERIAL NOT NULL PRIMARY KEY,
    IMAGE_NAME VARCHAR(200),
    UUID_USER INT NOT NULL,
    ENCODE_IMAGE TEXT NOT NULL,
    FOREIGN KEY (UUID_USER) REFERENCES USER_MEMBER(UUID_USER_MEMBER) ON DELETE CASCADE
);